-- public.clientes definition

-- Drop table

-- DROP TABLE public.clientes;

CREATE TABLE public.clientes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	identificacion int8 NOT NULL,
	nombres varchar NOT NULL,
	direccion varchar NOT NULL,
	telefono int8 NOT NULL,
	correo varchar NOT NULL,
	CONSTRAINT clientes_pk PRIMARY KEY (id)
);

-- public.cajero definition

-- Drop table

-- DROP TABLE public.cajero;

CREATE TABLE public.cajero (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	identificacion int8 NOT NULL,
	nombres varchar NOT NULL,
	direccion varchar NOT NULL,
	correo varchar NOT NULL,
	telefono int8 NOT NULL,
	contraseña varchar NOT NULL,
	CONSTRAINT cajero_pk PRIMARY KEY (id)
);


-- public.producto definition

-- Drop table

-- DROP TABLE public.producto;

CREATE TABLE public.producto (
	id_producto int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(60) NOT NULL,
	precio int4 NOT NULL,
	stock int4 NOT NULL,
	imagen varchar NULL,
	CONSTRAINT producto_pk PRIMARY KEY (id_producto)
);
-- public.factura definition

-- Drop table

-- DROP TABLE public.factura;

CREATE TABLE public.factura (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_cliente int4 NOT NULL,
	id_cajero int4 NOT NULL,
	fecha timestamp NULL,
	totalpagar int4 NULL,
	CONSTRAINT factura_pk PRIMARY KEY (id)
);


-- public.factura foreign keys

ALTER TABLE public.factura ADD CONSTRAINT factura_fk FOREIGN KEY (id_cajero) REFERENCES public.cajero(id);
ALTER TABLE public.factura ADD CONSTRAINT factura_fk_1 FOREIGN KEY (id_cliente) REFERENCES public.clientes(id);


-- public.detalle_factura definition

-- Drop table

-- DROP TABLE public.detalle_factura;

CREATE TABLE public.detalle_factura (
	id_factura int4 NOT NULL,
	id_producto int4 NOT NULL,
	nombre varchar NOT NULL,
	cantidad int4 NOT NULL,
	precio_unitario int4 NOT NULL,
	total int4 NOT NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	CONSTRAINT detalle_factura_pk PRIMARY KEY (id)
);

CREATE OR REPLACE FUNCTION public.stock_producto()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
	UPDATE producto  SET stock  = stock - new.CANTIDAD  WHERE id_producto = new.id_producto;
return new; 
end
$function$
;

-- Table Triggers

create trigger stockproductos after
insert
    on
    public.detalle_factura for each row execute procedure stock_producto();


-- public.detalle_factura foreign keys

ALTER TABLE public.detalle_factura ADD CONSTRAINT detalle_factura_fk FOREIGN KEY (id_factura) REFERENCES public.factura(id);
ALTER TABLE public.detalle_factura ADD CONSTRAINT detalle_factura_fk_1 FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto);
